### ISSUE TITLE
Atom 1.54.0 fails to open after running toggleframe.js

### ISSUE THREAD

**Issue by ahallicks** [sean-codes/atom-windows-titlebar#13]
I've just had an update to 1.54.0 of Atom on Windows and when I run toggleframe.js everything works until I go to reopen Atom at which point nothing happens. The app doesn't up but I get no errors or anything.

I believe it's something to do with this package because a clean install of the same version does work okay.

To reproduce:

1. Install Atom 1.54.0
2. Run `node toggleframe.js`
3. Reopen Atom when it completes
4. Nothing happens

**Comment by ahallicks** [comment]
I've just found https://github.com/atom/atom/issues/20677 which is actually another way to have the titlebar not show on Windows so negates the need to run toggleframe.js \o/.

**Comment by sean-codes** [comment]
Hi, sorry for such a late response! I updated the README as atom now has setting under code to set the titlebar to hidden!
