### ISSUE TITLE
"Alt" key doesn't always work

### ISSUE THREAD

**Issue by davidedellagiustina** [sean-codes/atom-windows-titlebar#2]
On my Windows 10 Pro laptop, if I start Atom with your theme, pressing "Alt" key shows the default menu, but if I switch window using the "alt + tab" keys, and then switch back to Atom with the same method, "Alt" stops working and the menu doesn't show up anymore. Need to restart Atom to get it work again.
Can this be solved?
Thank you in advance :)

**Comment by IiroP** [comment]
Same happens for me (but not always, just sometimes) Win10 Home

**Comment by davidedellagiustina** [comment]
Don't ask me how, but I just discovered that, when the menu does not open with "alt", if you press "alt + win + t" (I guess it's the same with "alt + cmd + t") it does nothing but it makes the "alt" key work again.

Yes, I'm messing up with Atom and keyboard shortcuts ahah

**Comment by IiroP** [comment]
@dgdav99 That doesn't work for me

**Comment by davidedellagiustina** [comment]
@IiroP Let's wait for the dev to answer, and see if he has a better explanation 😅

**Comment by sean-codes** [comment]
@dgdav99 @IiroP Fix for this is up! I was using a silly trick to get that menu to show up. I moved it to a proper atom keybinding! Please let me know if you run into any issues or have any questions!

**Comment by davidedellagiustina** [comment]
Updated and it works, thank you 😄 
But now there's a minor problem: when hitting "alt + tab" to change window, the menu appears as soon as I press "alt" (even before pressing "tab")...

**Comment by sean-codes** [comment]
@dgdav99 Okay was sort of why I was using the trick. I'm going to take a second look!

**Comment by sean-codes** [comment]
@dgdav99 Looks like there is a new way for binds so we can add a `^` for th ealt key this should fix us up! Please let me know if still experiencing after update!

**Comment by davidedellagiustina** [comment]
Yippie!
Updated, restarted & perfectly working!
Thank you sir for really fast fix!

**Comment by davidedellagiustina** [comment]
Last update: when using AltGr (for any key combination, like to write a square bracket) triggers the menu...

**Comment by sean-codes** [comment]
@dgdav99 Darn we are going rounds with this. New update might be the winner :]

**Comment by sean-codes** [comment]
@dgdav99 By the way I appreciate you sticking with me and help with testing!

**Comment by davidedellagiustina** [comment]
@sean-codes Updated to 0.11.0 (lmao just yeterday it was 0.9.0) and looks like it's working 😄 
Anyway, I'm happy you consider this testing, but I'm actually just doing some coding stuff these days and I find that menu bar popping up when I don't need it and not showing up when I need it quite annoying 🤣 
Glad you like my attempt to help 😄
