### ISSUE TITLE
Double Menu when update

### ISSUE THREAD

**Issue by EvanTideswell** [sean-codes/atom-windows-titlebar#3]
I have noticed that when you update atom the plugin needs to be turned off then on again manually in order for it to display correctly, the way that it displays when you do an update it shows the default titlebar and the plugins titlebar at the same time.

**Comment by sean-codes** [comment]
Hi @EvanTideswell! Atom switched back to using ASAR making toggling the frame a bit difficult. Please follow the new instructions in the README

### 1. Close Atom
make sure all atom windows are closed

### 2. Terminal/CMD to your atom/app-X.XX.X folder
run `cd C:\Users\{user}\AppData\Local\atom\app-{version}`

### 3. npm install asar
run `npm install asar`

### 4. node toggleframe.js
run `node toggleframe.js`

### 5. Open atom!
Open atom!
