### ISSUE TITLE
Not working in Atom Beta

### ISSUE THREAD

**Issue by ahallicks** [sean-codes/atom-windows-titlebar#4]
I know this is probably a little soon but I had a play with the Atom beta today (1.21.0-beta1) and this package (which I LOVE by the way) works except the bit that auto-hides the normal frame. I *think* this is probably because it looks like the beta uses asar to zip up the contents of the app so there is no simple way of modifying the BrowserWindow.

This means that I always had both menus active and couldn't disable the main one at all.

**Comment by sean-codes** [comment]
@ahallicks Thank you, will be looking it this! :]

**Comment by sean-codes** [comment]
@ahallicks Atom switched back to ASAR that made doing this automatically a bit difficult. If you would like to continue using this package please read the new instructions in the README.md!

1. Close Atom

make sure all atom windows are closed

2. Terminal/CMD to your atom/app-X.XX.X folder

run cd C:\Users\{user}\AppData\Local\atom\app-{version}

3. npm install asar

run npm install asar

4. node toggleframe.js

run node toggleframe.js

5. Open atom!

Open atom!

**Comment by ahallicks** [comment]
Thanks @sean-codes. That worked. However, you appear to be missing a step in your updated instructions.

I had to copy `toggleframe.js` into the `C:\Users{user}\AppData\Local\atom\app-{version}` before it would work.
