### ISSUE TITLE
Windows default titlebar not hiding anymore

### ISSUE THREAD

**Issue by davidedellagiustina** [sean-codes/atom-windows-titlebar#5]
It looks like it doesn't hide the default Windows titlebar anymore... (0.13.0)
Already tried to check and uncheck the option several times, and even rebooted atom more than once.

**Comment by mettaworldjon** [comment]
It seems as though the file :
"C:\Users\{username}\AppData\Local\atom\app{version}\resources\app\src\main-process\atom-window.js"
is missing if we find that file we fix the problem.

**Comment by sean-codes** [comment]
@dgdav99 @mettaworldjon Atom switched back to ASAR that made doing this automatically a bit difficult. If you would like to continue using this package please read the new instructions in the README.md!

### 1. Close Atom
make sure all atom windows are closed

### 2. Terminal/CMD to your atom/app-X.XX.X folder
run `cd C:\Users\{user}\AppData\Local\atom\app-{version}`

### 3. npm install asar
run `npm install asar`

### 4. node toggleframe.js
run `node toggleframe.js`

### 5. Open atom!
Open atom!

**Comment by davidedellagiustina** [comment]
Thank you!
But.. do I have to have node.js installed?

Della Giustina Davide

Il 16 ott 2017 22:22, "Sean Codes" <notifications@github.com> ha scritto:

**Comment by sean-codes** [comment]
@dgdav99 Yes. Also the ASAR package

**Comment by KiraiEEE** [comment]
try this https://atom.io/packages/no-title-bar
