### ISSUE TITLE
The CMD commands don't work

### ISSUE THREAD

**Issue by Iuvaten-de** [sean-codes/atom-windows-titlebar#6]
I tried to execute the CMD commands. But CMD did not recognized the commands :(

**Comment by swaffoz** [comment]
What output do you get when you run the commands?

**Comment by Musteblume** [comment]
You have to install node.js

**Comment by robbycbennett** [comment]
Here's an easy way to use atom-windows-titlebar:
1. Install title-bar-replacer
2. Remove the Windows title bar using this extension.
3. Uninstall title-bar-replacer.
