### ISSUE TITLE
New Atom version - default status bar not hiding

### ISSUE THREAD

**Issue by davidedellagiustina** [sean-codes/atom-windows-titlebar#7]
Updated Atom to v1.21.2 (x64), and default Windows bar doesn't hide... even after disabling/enabling the package and restarting atom.
😕

**Comment by sean-codes** [comment]
Any time Atom updates with will override changes to its app.asar. You have to use the instructions provided in the readme to get it working again. Unfortunately at this time there is not an automatic way to do this because atom needs to be closed to make changes to its app.asar
